# Generated by Django 4.0 on 2022-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sem', models.IntegerField()),
                ('program', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['roll'],
            },
        ),
    ]
