# Generated by Django 4.0 on 2022-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_auto_20200516_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='image',
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
