# Generated by Django 4.0 on 2022-11-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='career_prospectus',
        ),
        migrations.AddField(
            model_name='message',
            name='roll',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20)),
                ('sem', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
        ),
    ]
