# Generated by Django 4.0 on 2022-11-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_remove_program_career_prospectus_message_roll_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='roll',
            field=models.CharField(max_length=20),
        ),
    ]
