# Generated by Django 4.0 on 2022-11-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_message_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='program',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='programs',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
