# Generated by Django 4.0 on 2022-11-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_semester_program_remove_semester_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('desc', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='programs',
            field=models.ManyToManyField(to='academics.Program'),
        ),
    ]
