# Generated by Django 4.0 on 2022-11-11 15:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_program_subject_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
                ('subjects', models.ManyToManyField(to='academics.Subject')),
            ],
        ),
    ]
