# Generated by Django 4.0 on 2022-11-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_faculty_alter_grades_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
